[package]
name = "rosac_sema"
description = "The semantic analyzer of the Rosa Compiler."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rosa_comm.workspace = true
rosa_errors.workspace = true
rosac_parser.workspace = true

