[package]
name = "rosac_lexer"
description = "Lexing of Rosa source code into Tokens."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rosa_comm.workspace = true
