[workspace]
members = [
  "compiler/rosa_lexer",
  "compiler/rosac",
]

resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"
authors = ["Thibault V. (@Larsouille25)"]

[workspace.dependencies]
rosac = { path = "compiler/rosac" }
rosa_lexer = { path = "compiler/rosa_lexer"}
