[workspace]
members = [
  "compiler/rosa_errors",
  "compiler/rosac_lexer",
  "compiler/rosac",
  "compiler/rosa_comm",
]

resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"
authors = ["Thibault V. (@Larsouille25)"]

[workspace.dependencies]
rosac = { path = "compiler/rosac" }
rosac_lexer = { path = "compiler/rosac_lexer"}
rosa_errors = { path = "compiler/rosa_errors"}
rosa_comm = { path = "compiler/rosa_comm"}

termcolor = "1.4.1"
