[package]
name = "rosac"
description = "Rosa Compiler utility."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rosac_lexer.workspace = true
