[package]
name = "rosa_comm"
description = "Common utilities and data structures used in the compiler."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
