[package]
name = "rosa_errors"
description = "Crate responsible for the error handling in the Rosa compiler."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rosa_comm.workspace = true

termcolor.workspace = true
